const crimsonRelato = [
  { type: "heading", text: "Crimson: donde todos tenemos una historia para contar" },
  { type: "paragraph", text: "Hay lugares que uno puede dejar de visitar." },
  { type: "paragraph", text: "Y hay otros que nunca se van." },
  { type: "paragraph", text: "Quedan ahí, guardados en algún rincón de la memoria, esperando apenas una palabra, una canción, una fotografía vieja para volver a abrir sus puertas." },
  { type: "paragraph", text: "Y en Jesús María hay una palabra capaz de hacer exactamente eso:" },
  { type: "paragraph", text: "Crimson." },
  { type: "paragraph", text: "Decilo delante de alguien que haya sido joven por aquellos años y fijate qué pasa." },
  { type: "paragraph", text: "Primero aparece una sonrisa." },
  { type: "paragraph", text: "Después seguramente un:" },
  { type: "paragraph", text: "—¡Uhhh... Crimson!" },
  { type: "paragraph", text: "Y enseguida viene alguna historia." },
  { type: "paragraph", text: "Porque alcanza con nombrarlo para que, por un ratito, volvamos a tener diecisiete, dieciocho, veinte años." },
  { type: "paragraph", text: "Otra vez es sábado." },
  { type: "paragraph", text: "Otra vez estamos mirando el reloj." },
  { type: "paragraph", text: "Otra vez suena música en alguna pieza mientras elegimos qué ponernos." },
  { type: "paragraph", text: "Y otra vez aparece la pregunta que ponía en marcha todo el operativo:" },
  { type: "paragraph", text: "—¿Qué hacemos esta noche?" },
  { type: "paragraph", text: "Como si hiciera falta preguntar." },
  { type: "paragraph", text: "¡Vamos a Crimson!" },
  { type: "paragraph", text: "Y listo." },
  { type: "paragraph", text: "No había grupo de WhatsApp." },
  { type: "paragraph", text: "No había ubicación en tiempo real." },
  { type: "paragraph", text: "No había que mandar veinte mensajes para organizarse." },
  { type: "paragraph", text: "De alguna manera —que hoy resulta casi inexplicable— todos terminábamos encontrándonos." },
  { type: "heading", text: "Antes de Crimson... estaba la previa" },
  { type: "paragraph", text: "Porque ir a Crimson no era simplemente ir a bailar." },
  { type: "paragraph", text: "Era un ritual." },
  { type: "paragraph", text: "Y como todo buen ritual, empezaba varias horas antes." },
  { type: "paragraph", text: "Primero la ducha." },
  { type: "paragraph", text: "Después el perfume." },
  { type: "paragraph", text: "Después la ropa arriba de la cama." },
  { type: "paragraph", text: "Y ahí comenzaba el primer problema serio de la noche:" },
  { type: "paragraph", text: "La camisa blanca." },
  { type: "paragraph", text: "La de jean." },
  { type: "paragraph", text: "La de rayas." },
  { type: "paragraph", text: "El pantalón nevado recién comprado." },
  { type: "paragraph", text: "Las Topper impecables." },
  { type: "paragraph", text: "La campera de cuero." },
  { type: "paragraph", text: "Uno se miraba al espejo de frente." },
  { type: "paragraph", text: "De costado." },
  { type: "paragraph", text: "Otra vez de frente." },
  { type: "paragraph", text: "Se acomodaba el pelo." },
  { type: "paragraph", text: "Se alejaba un poquito." },
  { type: "paragraph", text: "Volvía." },
  { type: "paragraph", text: "—¿Está bien esto?" },
  { type: "paragraph", text: "—Sí, culiaa… ¡dale que nos vamos!" },
  { type: "paragraph", text: "—Pará, guaso, ya estoy." },
  { type: "paragraph", text: "No estaba." },
  { type: "paragraph", text: "Faltaban por lo menos veinte minutos." },
  { type: "paragraph", text: "Y el pelo merecería un capítulo aparte." },
  { type: "paragraph", text: "Había algunos jopos que desafiaban directamente las leyes de la gravedad." },
  { type: "paragraph", text: "Flequillos capaces de resistir viento norte, tormenta y una noche completa bailando." },
  { type: "paragraph", text: "Spray." },
  { type: "paragraph", text: "Gel." },
  { type: "paragraph", text: "Fijador." },
  { type: "paragraph", text: "Lo que hubiera." },
  { type: "paragraph", text: "Había que llegar impecable." },
  { type: "paragraph", text: "Porque uno nunca sabía..." },
  { type: "paragraph", text: "Capaz que esa noche aparecía \"esa\" persona." },
  { type: "paragraph", text: "Y si aparecía, había que estar preparado." },
  { type: "paragraph", text: "Aunque después no nos animáramos ni a saludarla." },
  { type: "paragraph", text: "Después empezaba la logística para juntar la barra." },
  { type: "paragraph", text: "Porque nadie iba solo." },
  { type: "paragraph", text: "Había que pasar a buscar a uno." },
  { type: "paragraph", text: "Esperar al otro." },
  { type: "paragraph", text: "Uno todavía estaba cenando." },
  { type: "paragraph", text: "Otro no encontraba las llaves." },
  { type: "paragraph", text: "Otro estaba bañándose." },
  { type: "paragraph", text: "Y nunca faltaba el famoso:" },
  { type: "paragraph", text: "—Salgo en cinco minutos." },
  { type: "paragraph", text: "¡Sí, cómo no!" },
  { type: "paragraph", text: "Esos cinco minutos podían durar tranquilamente media hora." },
  { type: "paragraph", text: "Y mientras tanto los demás afuera:" },
  { type: "paragraph", text: "—¡Dale, culiau!" },
  { type: "paragraph", text: "—¡¡¡Ya voy!!!" },
  { type: "paragraph", text: "Ese \"ya voy\" merece estar entre las grandes mentiras de nuestra juventud." },
  { type: "heading", text: "Y finalmente... Crimson" },
  { type: "paragraph", text: "Había algo especial en el momento de entrar." },
  { type: "paragraph", text: "Las luces." },
  { type: "paragraph", text: "La música." },
  { type: "paragraph", text: "El ruido." },
  { type: "paragraph", text: "El humo." },
  { type: "paragraph", text: "La gente." },
  { type: "paragraph", text: "Las caras conocidas." },
  { type: "paragraph", text: "Y automáticamente empezaba el verdadero reconocimiento del terreno." },
  { type: "paragraph", text: "Porque digamos la verdad de una vez..." },
  { type: "paragraph", text: "La mitad iba a bailar." },
  { type: "paragraph", text: "La otra mitad iba a ver quién había ido." },
  { type: "paragraph", text: "Y había un tercer grupo cuyos integrantes tenían objetivos mucho más específicos." },
  { type: "paragraph", text: "Los famosos busca parejas." },
  { type: "paragraph", text: "El guaso entraba y antes de escuchar el primer tema ya había realizado un relevamiento completo del boliche." },
  { type: "paragraph", text: "—¿Viste quién vino?" },
  { type: "paragraph", text: "—¿Quién?" },
  { type: "paragraph", text: "—La de allá." },
  { type: "paragraph", text: "—¿Cuál?" },
  { type: "paragraph", text: "—¡La de allá, culiau! ¡No mirés ahora!" },
  { type: "paragraph", text: "Y por supuesto..." },
  { type: "paragraph", text: "los cuatro miraban al mismo tiempo." },
  { type: "paragraph", text: "Disimulo absoluto." },
  { type: "paragraph", text: "Después comenzaban las vueltas." },
  { type: "paragraph", text: "Una." },
  { type: "paragraph", text: "Dos." },
  { type: "paragraph", text: "Cinco." },
  { type: "paragraph", text: "Quince." },
  { type: "paragraph", text: "Había tipos que caminaban más kilómetros dentro de Crimson un sábado a la noche que durante toda la semana." },
  { type: "paragraph", text: "Pero siempre, por esas casualidades inexplicables de la vida..." },
  { type: "paragraph", text: "pasaban por el mismo lugar." },
  { type: "paragraph", text: "—Che... ¿no es la tercera vez que pasamos por acá?" },
  { type: "paragraph", text: "—No, qué va..." },
  { type: "paragraph", text: "Era la séptima." },
  { type: "paragraph", text: "Porque justo ahí estaba ella." },
  { type: "paragraph", text: "Y nosotros nos hacíamos los distraídos." },
  { type: "paragraph", text: "\"No, si yo vine con los vagos nomás...\"" },
  { type: "paragraph", text: "Sí." },
  { type: "paragraph", text: "Claro." },
  { type: "paragraph", text: "Con los vagos." },
  { type: "paragraph", text: "Pero desde que habías entrado estabas mirando exactamente hacia el mismo rincón." },
  { type: "heading", text: "El ecosistema de Crimson" },
  { type: "paragraph", text: "Toda barra tenía sus personajes." },
  { type: "paragraph", text: "Estaba el bailarín." },
  { type: "paragraph", text: "El que apenas sonaba el primer tema ya estaba en la pista." },
  { type: "paragraph", text: "Estaba el tímido." },
  { type: "paragraph", text: "Ese podía pasar toda la noche estudiando la situación." },
  { type: "paragraph", text: "Estaba el que conocía a todo el mundo." },
  { type: "paragraph", text: "Entrabas con él y tardabas media hora en recorrer diez metros." },
  { type: "paragraph", text: "—¡Negrooo!" },
  { type: "paragraph", text: "Abrazo." },
  { type: "paragraph", text: "Cinco pasos." },
  { type: "paragraph", text: "—¡Guaso! ¿Qué hacés?" },
  { type: "paragraph", text: "Otro abrazo." },
  { type: "paragraph", text: "Tres pasos." },
  { type: "paragraph", text: "—¡Ehhh, loco!" },
  { type: "paragraph", text: "Otro más." },
  { type: "paragraph", text: "Uno pensaba:" },
  { type: "paragraph", text: "\"¿Este culiau conoce a todo Jesús María?\"" },
  { type: "paragraph", text: "Probablemente sí." },
  { type: "paragraph", text: "Después estaba el que tenía llegada al DJ." },
  { type: "paragraph", text: "No sabemos exactamente qué beneficio otorgaba aquello..." },
  { type: "paragraph", text: "Pero él lo hacía saber." },
  { type: "paragraph", text: "—Al DJ lo conozco yo." },
  { type: "paragraph", text: "Perfecto." },
  { type: "paragraph", text: "Todos más tranquilos." },
  { type: "paragraph", text: "También estaba el galán de la barra." },
  { type: "paragraph", text: "O por lo menos él estaba convencido de que lo era." },
  { type: "paragraph", text: "Antes de salir ya anunciaba:" },
  { type: "paragraph", text: "—Hoy levanto seguro." },
  { type: "paragraph", text: "A las cuatro de la mañana estaba comiendo algo con nosotros." },
  { type: "paragraph", text: "Solo." },
  { type: "paragraph", text: "Pero no había problema." },
  { type: "paragraph", text: "El sábado siguiente volvía a intentarlo." },
  { type: "paragraph", text: "La fe mueve montañas." },
  { type: "paragraph", text: "Y estaba el misterioso." },
  { type: "paragraph", text: "El que desaparecía media hora." },
  { type: "paragraph", text: "Volvía acomodándose la camisa y con una sonrisa sospechosa." },
  { type: "paragraph", text: "—¿Dónde estabas?" },
  { type: "paragraph", text: "—Después les cuento." },
  { type: "paragraph", text: "Nunca contaba nada." },
  { type: "paragraph", text: "Pero nosotros, por amistad, le inventábamos una historia extraordinaria." },
  { type: "heading", text: "Y estaban... los bailarines" },
  { type: "paragraph", text: "Había algunos que realmente sabían bailar." },
  { type: "paragraph", text: "Esos merecen nuestro respeto." },
  { type: "paragraph", text: "Y después..." },
  { type: "paragraph", text: "estábamos los demás." },
  { type: "paragraph", text: "Había uno que tenía un paso para absolutamente todo." },
  { type: "paragraph", text: "Rock." },
  { type: "paragraph", text: "Disco." },
  { type: "paragraph", text: "Pop." },
  { type: "paragraph", text: "Cuarteto." },
  { type: "paragraph", text: "Tema rápido." },
  { type: "paragraph", text: "Tema lento." },
  { type: "paragraph", text: "Daba igual." },
  { type: "paragraph", text: "El mismo paso." },
  { type: "paragraph", text: "Pero el guaso lo hacía con semejante convicción que uno terminaba pensando:" },
  { type: "paragraph", text: "\"Mirá vos... debe ser un paso nuevo.\"" },
  { type: "paragraph", text: "Y siempre estaba aquel que arrancaba bastante moderado." },
  { type: "paragraph", text: "Pero después de un par de tragos..." },
  { type: "paragraph", text: "se transformaba." },
  { type: "paragraph", text: "De pronto John Travolta era un aprendiz al lado suyo." },
  { type: "paragraph", text: "El tipo ocupaba el centro de la pista." },
  { type: "paragraph", text: "Giraba." },
  { type: "paragraph", text: "Se agachaba." },
  { type: "paragraph", text: "Levantaba los brazos." },
  { type: "paragraph", text: "Improvisaba cosas que probablemente nunca antes había hecho un ser humano." },
  { type: "paragraph", text: "Y los amigos desde un costado:" },
  { type: "paragraph", text: "—Dejalo..." },
  { type: "paragraph", text: "—Está contento." },
  { type: "paragraph", text: "—¿Contento?" },
  { type: "paragraph", text: "—Bueno... está entonado el negro." },
  { type: "paragraph", text: "Al otro día, curiosamente, él recordaba una actuación bastante diferente." },
  { type: "paragraph", text: "—Anoche la rompí." },
  { type: "paragraph", text: "—Sí, guaso..." },
  { type: "paragraph", text: "Rompiste algo seguro." },
  { type: "heading", text: "\"Hoy no tomo\"" },
  { type: "paragraph", text: "Otra frase histórica." },
  { type: "paragraph", text: "Todos alguna vez la pronunciamos." },
  { type: "paragraph", text: "—Hoy no tomo nada." },
  { type: "paragraph", text: "Después venía uno." },
  { type: "paragraph", text: "—Dale, uno solo." },
  { type: "paragraph", text: "Bueno..." },
  { type: "paragraph", text: "Uno." },
  { type: "paragraph", text: "Después otro." },
  { type: "paragraph", text: "Y otro." },
  { type: "paragraph", text: "Y aparecía ese momento mágico de la noche en el que aquel amigo normalmente reservado descubría cuánto quería a todo el mundo." },
  { type: "paragraph", text: "—Escuchame..." },
  { type: "paragraph", text: "—¿Qué?" },
  { type: "paragraph", text: "—Vos sabés que yo te quiero, ¿no?" },
  { type: "paragraph", text: "—Sí, negro." },
  { type: "paragraph", text: "—No, pero escuchame..." },
  { type: "paragraph", text: "—Sí, ya sé." },
  { type: "paragraph", text: "—No, vos no entendés..." },
  { type: "paragraph", text: "Y ahí arrancaba una conversación filosófica que podía durar cuarenta minutos." },
  { type: "paragraph", text: "Al día siguiente:" },
  { type: "paragraph", text: "—Che... ¿qué hice anoche?" },
  { type: "paragraph", text: "—Nada." },
  { type: "paragraph", text: "Los amigos también servían para eso." },
  { type: "paragraph", text: "Y algunas cosas..." },
  { type: "paragraph", text: "Bueno." },
  { type: "paragraph", text: "Algunas cosas quedarán para siempre entre aquellas paredes." },
  { type: "paragraph", text: "Porque una cosa es hacer memoria..." },
  { type: "paragraph", text: "Y otra muy distinta es entregar compañeros cuarenta años después." },
  { type: "paragraph", text: "Hay códigos." },
  { type: "heading", text: "Y de pronto... los lentos" },
  { type: "paragraph", text: "Ahí cambiaba todo." },
  { type: "paragraph", text: "Empezaban los primeros acordes y había quienes sabían perfectamente qué hacer." },
  { type: "paragraph", text: "Se levantaban." },
  { type: "paragraph", text: "Cruzaban la pista." },
  { type: "paragraph", text: "Y encaraban." },
  { type: "paragraph", text: "Después estábamos los otros." },
  { type: "paragraph", text: "Los pensadores." },
  { type: "paragraph", text: "Los estrategas." },
  { type: "paragraph", text: "Los que necesitábamos realizar un análisis completo de riesgo antes de caminar quince metros." },
  { type: "paragraph", text: "\"Voy.\"" },
  { type: "paragraph", text: "Dos minutos después:" },
  { type: "paragraph", text: "\"Ahora voy.\"" },
  { type: "paragraph", text: "Después:" },
  { type: "paragraph", text: "\"Cuando termine este tema.\"" },
  { type: "paragraph", text: "Y entonces empezaba otro lento." },
  { type: "paragraph", text: "\"Este está mejor.\"" },
  { type: "paragraph", text: "Mientras tanto aparecía otro guaso, caminaba directamente hacia ella y la sacaba a bailar." },
  { type: "paragraph", text: "Y nosotros:" },
  { type: "paragraph", text: "—No importa." },
  { type: "paragraph", text: "—¿No ibas a ir?" },
  { type: "paragraph", text: "—Nahhh... al final no tenía ganas." },
  { type: "paragraph", text: "¡Sí, cómo no!" },
  { type: "paragraph", text: "Por dentro queríamos matar al otro." },
  { type: "paragraph", text: "Y estaba el amigo que ayudaba." },
  { type: "paragraph", text: "—Dale, guaso. Andá." },
  { type: "paragraph", text: "—No." },
  { type: "paragraph", text: "—Dale." },
  { type: "paragraph", text: "—¿Y si me dice que no?" },
  { type: "paragraph", text: "—¡Qué te va a decir que no!" },
  { type: "paragraph", text: "—Andá vos." },
  { type: "paragraph", text: "—¡Pero si a mí no me gusta!" },
  { type: "paragraph", text: "Grandes negociaciones diplomáticas de los años ochenta." },
  { type: "heading", text: "Éramos jóvenes... y no necesitábamos demostrarlo" },
  { type: "paragraph", text: "Hay algo que estas fotografías muestran mejor que cualquier relato." },
  { type: "paragraph", text: "No había celulares." },
  { type: "paragraph", text: "No había Instagram." },
  { type: "paragraph", text: "No había historias." },
  { type: "paragraph", text: "No había selfies." },
  { type: "paragraph", text: "No había filtros." },
  { type: "paragraph", text: "Nadie estaba pensando:" },
  { type: "paragraph", text: "\"Esto lo tengo que subir.\"" },
  { type: "paragraph", text: "Estábamos ahí." },
  { type: "paragraph", text: "Nada más." },
  { type: "paragraph", text: "Si querías saber quién había salido..." },
  { type: "paragraph", text: "tenías que salir." },
  { type: "paragraph", text: "Si querías hablar con alguien..." },
  { type: "paragraph", text: "Tenías que acercarte." },
  { type: "paragraph", text: "Si te gustaba una chica o un muchacho..." },
  { type: "paragraph", text: "No había corazoncito." },
  { type: "paragraph", text: "No había mensaje privado." },
  { type: "paragraph", text: "Había que juntar coraje." },
  { type: "paragraph", text: "Cruzar la pista." },
  { type: "paragraph", text: "Y decir:" },
  { type: "paragraph", text: "—¿Bailamos?" },
  { type: "paragraph", text: "Parece sencillo ahora." },
  { type: "paragraph", text: "¡Las pelotas!" },
  { type: "paragraph", text: "Había que animarse." },
  { type: "paragraph", text: "Por eso estas fotografías tienen algo especial." },
  { type: "paragraph", text: "Son pocas." },
  { type: "paragraph", text: "Muchas están desenfocadas." },
  { type: "paragraph", text: "Otras oscuras." },
  { type: "paragraph", text: "En algunas alguien salió con los ojos cerrados." },
  { type: "paragraph", text: "En otras hay uno que justo pasó por adelante." },
  { type: "paragraph", text: "Pero son nuestras." },
  { type: "paragraph", text: "Y nadie que aparece en ellas estaba posando pensando que esa imagen algún día terminaría circulando por Internet." },
  { type: "paragraph", text: "Mucho menos que cuarenta años después íbamos a estar mirándola juntos." },
  { type: "heading", text: "Ahora viene la parte peligrosa..." },
  { type: "paragraph", text: "La galería de fotos." },
  { type: "paragraph", text: "Porque sabemos perfectamente lo que vas a hacer." },
  { type: "paragraph", text: "No te hagás el distraído." },
  { type: "paragraph", text: "Primero te vas a buscar vos." },
  { type: "paragraph", text: "Después vas a buscar a tus amigos." },
  { type: "paragraph", text: "Después a tus hermanos." },
  { type: "paragraph", text: "Después a aquel o aquella que..." },
  { type: "paragraph", text: "Bueno..." },
  { type: "paragraph", text: "vos sabés." },
  { type: "paragraph", text: "Y de repente:" },
  { type: "paragraph", text: "—¡¡¡Mirá quién está acá!!!" },
  { type: "paragraph", text: "Zoom." },
  { type: "paragraph", text: "Más zoom." },
  { type: "paragraph", text: "—¡No puede ser!" },
  { type: "paragraph", text: "Sí." },
  { type: "paragraph", text: "Es." },
  { type: "paragraph", text: "Y seguramente la foto viajará inmediatamente." },
  { type: "paragraph", text: "—¡Mirá la pinta que tenías!" },
  { type: "paragraph", text: "Y del otro lado llegará la respuesta:" },
  { type: "paragraph", text: "—¡Callate, culiau! ¡Mirá cómo estabas vos!" },
  { type: "paragraph", text: "Y empezarán los mensajes." },
  { type: "paragraph", text: "—¿Quién era el de atrás?" },
  { type: "paragraph", text: "—¿No es Fulano?" },
  { type: "paragraph", text: "—¡Sí!" },
  { type: "paragraph", text: "—¿Y la chica de al lado?" },
  { type: "paragraph", text: "—Pará... creo que es..." },
  { type: "paragraph", text: "Y de pronto una fotografía que estuvo guardada cuarenta años habrá conseguido algo extraordinario:" },
  { type: "paragraph", text: "volver a juntar a la barra." },
  { type: "paragraph", text: "A algunos de los que aparecen en estas fotos los conocemos perfectamente." },
  { type: "paragraph", text: "Y por una cuestión de amistad, respeto y, principalmente, para evitar problemas judiciales cuatro décadas después..." },
  { type: "paragraph", text: "vamos a preservar ciertas identidades." },
  { type: "paragraph", text: "Ahora..." },
  { type: "paragraph", text: "Si ustedes los reconocen..." },
  { type: "paragraph", text: "Nosotros no podemos hacer nada." },
  { type: "heading", text: "Pero detrás de todas las cargadas hay algo más" },
  { type: "paragraph", text: "Cuando éramos jóvenes pensábamos que aquellas noches iban a durar para siempre." },
  { type: "paragraph", text: "Que siempre habría otro sábado." },
  { type: "paragraph", text: "Otra previa." },
  { type: "paragraph", text: "Otro baile." },
  { type: "paragraph", text: "Otra oportunidad." },
  { type: "paragraph", text: "Otra canción." },
  { type: "paragraph", text: "Otra vuelta por la pista." },
  { type: "paragraph", text: "No sabíamos que mientras nos reíamos, bailábamos, nos enamorábamos, nos desenamorábamos, tomábamos algún trago de más o esperábamos aquel lento..." },
  { type: "paragraph", text: "estábamos fabricando recuerdos." },
  { type: "paragraph", text: "Y eso es quizás lo que emociona cuando hoy vemos estas fotografías." },
  { type: "paragraph", text: "No estamos mirando solamente Crimson." },
  { type: "paragraph", text: "Nos estamos mirando a nosotros mismos." },
  { type: "paragraph", text: "A quienes fuimos." },
  { type: "paragraph", text: "A nuestros amigos." },
  { type: "paragraph", text: "A los que todavía están." },
  { type: "paragraph", text: "Y también, inevitablemente, a algunos que ya no están con nosotros." },
  { type: "paragraph", text: "Y por un instante..." },
  { type: "paragraph", text: "vuelven todos." },
  { type: "paragraph", text: "Crimson fue el escenario." },
  { type: "paragraph", text: "Los protagonistas siempre fuimos nosotros." },
  { type: "paragraph", text: "Los que llegábamos temprano." },
  { type: "paragraph", text: "Los que llegaban cuando la noche ya estaba armada." },
  { type: "paragraph", text: "Los bailarines." },
  { type: "paragraph", text: "Los tímidos." },
  { type: "paragraph", text: "Los busca parejas." },
  { type: "paragraph", text: "Los enamorados." },
  { type: "paragraph", text: "Los que se volvían solos." },
  { type: "paragraph", text: "Los que consiguieron compañía." },
  { type: "paragraph", text: "Los que tomaron uno de más." },
  { type: "paragraph", text: "Los que juraban recordar todo." },
  { type: "paragraph", text: "Los que al día siguiente preguntaban:" },
  { type: "paragraph", text: "—Che... ¿anoche pasó algo?" },
  { type: "paragraph", text: "—No, negro. Quedate tranquilo." },
  { type: "paragraph", text: "Y sí había pasado." },
  { type: "paragraph", text: "Pero éramos amigos." },
  { type: "paragraph", text: "Quizás eso explique por qué basta pronunciar una palabra..." },
  { type: "paragraph", text: "Crimson." },
  { type: "paragraph", text: "Y aparece inmediatamente una sonrisa." },
  { type: "paragraph", text: "Porque no recordamos solamente un boliche." },
  { type: "paragraph", text: "Recordamos una edad." },
  { type: "paragraph", text: "Una barra." },
  { type: "paragraph", text: "Una canción." },
  { type: "paragraph", text: "Una mirada." },
  { type: "paragraph", text: "Un perfume." },
  { type: "paragraph", text: "Una camisa que creíamos espectacular." },
  { type: "paragraph", text: "Un peinado que hoy negaríamos ante escribano público." },
  { type: "paragraph", text: "Recordamos cuando faltaba toda una vida por delante y cada sábado parecía capaz de cambiarlo todo." },
  { type: "paragraph", text: "Y quizá nunca nos dimos cuenta..." },
  { type: "paragraph", text: "Pero entre todas aquellas risas, bailes, papelones, conquistas, rechazos, tragos, amigos y madrugadas..." },
  { type: "paragraph", text: "esas fueron algunas de las noches que nos hicieron grandes." },
  { type: "heading", text: "El confesionario de Crimson" },
  { type: "paragraph", text: "Ahora les toca a ustedes." },
  { type: "paragraph", text: "Porque nosotros podemos contar una parte." },
  { type: "paragraph", text: "La otra está guardada en la memoria de cada uno." },
  { type: "paragraph", text: "¿Quién era el más bailarín de la barra? ¿Quién decía \"ya salgo\" y hacía esperar a todos? ¿Quién recorría veinte veces la pista para pasar \"casualmente\" delante de alguien? ¿Quién era el galán... según él mismo? ¿Quién decía \"hoy no tomo\" y dos horas después quería abrazar hasta al DJ? ¿Quién era el eterno enamorado? ¿Quién se acuerda de una noche que todavía hoy, cuando se juntan, termina inevitablemente con un \"¿te acordás de aquella vez en Crimson...?\"?" },
  { type: "paragraph", text: "Y sobre todo:" },
  { type: "paragraph", text: "Buscate en las fotos." },
  { type: "paragraph", text: "Buscá a tus amigos." },
  { type: "paragraph", text: "Etiquetalos." },
  { type: "paragraph", text: "Mandales el artículo." },
  { type: "paragraph", text: "Contanos la anécdota." },
  { type: "paragraph", text: "Y si tenés fotografías guardadas de Crimson, compartilas con nosotros." },
  { type: "paragraph", text: "No importa si están oscuras, rayadas, dobladas o perdieron color." },
  { type: "paragraph", text: "Porque quizás en esa foto que lleva cuarenta años dentro de una caja..." },
  { type: "paragraph", text: "está guardado el sábado inolvidable de alguien más." },
  { type: "paragraph", text: "Entre todos podemos reconstruir el álbum de una generación." },
  { type: "paragraph", text: "Una generación que no necesitaba subir una historia para demostrar que había pasado una buena noche." },
  { type: "paragraph", text: "Porque la historia..." },
  { type: "paragraph", text: "la estábamos viviendo." },
  { type: "paragraph", text: "Y vaya si la vivimos." },
];

export default crimsonRelato;
